// generated by tools/build-stories.mjs from mockups/future_state_mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";
import spec from "../../pages/installer.md?raw";

export default {
  title: "Future state/Onboarding/Installer",
  tags: ["autodocs"],
  argTypes,
  args: { shell: "desktop", theme: "system", product: true, hash: "#/welcome/installer" },
  parameters: { docs: { description: { component: spec } } },
  render: view,
};

export const Loaded = { name: "Loaded", args: { state: "loaded" } };
export const LoadedMobile = { name: "Loaded · mobile", args: { state: "loaded", shell: "mobile" } };
