// generated by tools/build-stories.mjs from mockups/future_state_mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";
import spec from "../../pages/register-name.md?raw";

export default {
  title: "Future state/Register/Register agent · Name",
  tags: ["autodocs"],
  argTypes,
  args: { shell: "desktop", theme: "system", product: true, hash: "#/a-intel/core-platform/register/name" },
  parameters: { docs: { description: { component: spec } } },
  render: view,
};

export const Loaded = { name: "Loaded", args: { state: "loaded" } };
export const Loading = { name: "Loading", args: { state: "loading" } };
export const AccessDenied = { name: "Access denied", args: { state: "denied" } };
export const LoadedMobile = { name: "Loaded · mobile", args: { state: "loaded", shell: "mobile" } };
export const LoadingMobile = { name: "Loading · mobile", args: { state: "loading", shell: "mobile" } };
export const AccessDeniedMobile = { name: "Access denied · mobile", args: { state: "denied", shell: "mobile" } };
