/* V2 presentation layer. The original engine remains the owner of creation wizards. */
var V2 = {q:'',operator:'',harness:'',repo:'',status:'all',page:1,size:25,selected:new Set(),spend:'operator',runTab:'overview',coached:new Set(),coachingDrafts:{}};
var V2_RUNS = v2MakeRuns(RUNS, PEOPLE, AGENTS);
var v2OriginalSync=stgSyncHash;
stgSyncHash=function(r){if(r.page==='steering'&&!location.hash.split('/')[4])return;v2OriginalSync(r);};
var v2OriginalFleet=pFleet, v2OriginalRun=pRun, v2OriginalSteering=pSteering, v2OriginalSidebar=sidebar, v2OriginalRoute=route, v2OriginalRender=render;
function v2Base(){return '#/'+ORG.slug+'/'+S.ws;}
function v2RunUrl(r){return v2Base()+'/runs/'+r.id;}
function v2Time(iso){var t=v2Timestamp(iso);return '<time class="v2-time" datetime="'+h(t.iso)+'" title="UTC"><span>'+h(t.date)+'</span> <span>'+h(t.time)+'</span></time>';}
function v2Logo(key){if(!V2_HARNESSES[key])return '';return ['light','dark'].map(function(theme){return '<img class="v2-logo '+theme+'" alt="" width="25" height="25" src="'+V2_ASSETS[key+'-'+theme+'.svg']+'">';}).join('');}
function v2Harness(r){return '<div class="v2-harness">'+v2Logo(r.harness)+h(r.harnessLabel)+'</div><div class="v2-model">'+h(r.model)+'<br>'+h(r.effort?r.effort+' effort':'Effort not reported')+'</div>';}
function v2Person(r){return '<span class="v2-operator">'+personAv(r.op,23)+'<span>'+h(r.operator)+'</span></span>';}
function v2Status(r){var label={live:'Running',parked:'Awaiting approval',paused:'Paused',sealed:'Completed',halted:'Stopped',compacted:'Completed'};return '<span class="v2-status '+h(r.status)+'">'+(label[r.status]||h(r.status))+'</span>';}
function v2Money(r){return r.cost===null?'Not metered':usd(r.cost.toFixed(2));}
function v2Rows(){return V2_RUNS.filter(function(r){return r.ws===S.ws;}).sort(function(a,b){var rank={live:0,parked:1,paused:2};return (rank[a.status]??3)-(rank[b.status]??3)||b.started.localeCompare(a.started);});}
function v2Metric(label,value,note){return '<div class="v2-metric"><small>'+h(label)+'</small><strong>'+h(value)+'</strong><p>'+h(note)+'</p></div>';}
function v2Header(title,description,actions){return '<div class="phead"><div class="t"><p class="eyebrow">'+h(ws().name)+'</p><h1>'+h(title)+'</h1><p>'+h(description)+'</p></div><div class="acts">'+(actions||'')+'</div></div>';}
function v2Link(href,label,primary){return '<a class="btn'+(primary?' primary':'')+'" href="'+h(href)+'">'+h(label)+'</a>';}
function v2State(title){
 if(S.state==='loading')return v2Header(title,'Loading your workspace…')+skeleton();
 if(S.state==='error')return v2Header(title,'We couldn’t load this view.')+'<div class="panel v2-empty"><p>Your workspace data is temporarily unavailable.</p><button class="btn" onclick="S.state=\'loaded\';render()">Try again</button></div>';
 if(S.state==='denied')return v2Header(title,'Access is restricted.')+'<div class="panel v2-empty"><h2>You don’t have access to this view</h2><p>Contact your workspace administrator.</p></div>';
 return '';
}
function v2Change(key,value){V2[key]=value;V2.page=1;V2.selected.clear();render();}
function v2Search(value){V2.q=value;V2.page=1;V2.selected.clear();var input=document.getElementById('v2-search'),pos=input?input.selectionStart:value.length;render();input=document.getElementById('v2-search');if(input){input.focus();input.setSelectionRange(pos,pos);}}
function v2Select(id,checked){if(checked)V2.selected.add(id);else V2.selected.delete(id);render();}
function v2SelectPage(checked){v2Paginate(v2Filter(v2Rows(),V2),V2.page,V2.size).rows.forEach(function(r){if(checked)V2.selected.add(r.id);else V2.selected.delete(r.id);});render();}
function v2Steer(){openSteerFleet();if(V2.selected.size){S.steerSel={};v2Rows().filter(function(r){return V2.selected.has(r.id);}).forEach(function(r){S.steerSel[r.agent]=true;});render();}}
function v2Options(key,label,rows){var opts=new Map();rows.forEach(function(r){var value=r[key],text=key==='op'?r.operator:key==='harness'?r.harnessLabel:value;opts.set(value,text);});var stateKey=key==='op'?'operator':key;return '<label>'+label+'<select aria-label="Filter by '+label.toLowerCase()+'" onchange="v2Change(\''+stateKey+'\',this.value)"><option value="">All '+(label==='Harness'?'harnesses':label.toLowerCase()+'s')+'</option>'+Array.from(opts.entries()).sort(function(a,b){return a[1].localeCompare(b[1]);}).map(function(e){return '<option value="'+h(e[0])+'" '+(V2[stateKey]===e[0]?'selected':'')+'>'+h(e[1])+'</option>';}).join('')+'</select></label>';}
function v2TableRow(r){return '<tr data-run="'+h(r.id)+'"><td class="v2-select"><input type="checkbox" aria-label="Select '+h(r.title)+'" '+(V2.selected.has(r.id)?'checked':'')+' onchange="v2Select(\''+h(r.id)+'\',this.checked)"></td>'+
 '<td><a class="v2-title" href="'+v2RunUrl(r)+'">'+h(r.title)+'</a><p class="v2-description">'+h(r.description)+'</p>'+v2Status(r)+
 '<div class="v2-meta"><a href="'+v2Base()+'/repositories">'+h(r.repo)+'</a>'+(r.pr?'<a href="'+v2RunUrl(r)+'" title="Open pull request context">PR #'+r.pr+'</a>':'<span>No pull request</span>')+'</div>'+
 '<div class="v2-meta"><span class="v2-add">+'+r.added+'</span><span class="v2-remove">−'+r.removed+'</span><span>'+r.files+' files</span><span>'+h(r.agentName)+'</span></div></td>'+
 '<td>'+v2Harness(r)+v2Person(r)+'</td><td><div class="v2-cost">'+v2Money(r)+'</div><div class="v2-eff" title="Cached input tokens divided by total input tokens">'+Math.round(r.cached/r.input*100)+'% cache reuse</div><div class="v2-model">'+((r.input+r.output)/1000).toFixed(1)+'k tokens</div><div style="margin-top:12px">'+v2Time(r.started)+'</div></td></tr>';}
function v2Approvals(){var pending=APPROVALS.filter(function(a){return a.ws===S.ws&&apState(a.id).status==='pending';});return '<section class="panel" aria-label="Approvals"><div class="panel-h"><h2>Approvals <span class="v2-count">'+pending.length+'</span></h2></div>'+(pending.length?pending.slice(0,V2.allApprovals?pending.length:2).map(function(a){var ag=agent(a.agent);return '<div class="v2-card"><div class="v2-quiet">'+h(ag?ag.name:a.agent)+'</div><h3>'+h(a.tool.replace(/@.*/, '').replace(/.*__/,'').replaceAll('_',' ').replace(/^./,function(c){return c.toUpperCase();}))+'</h3><p>'+h(a.counterparty)+' · '+'Approval required'+'</p><div class="row"><a href="'+v2Base()+'/runs/'+h(a.run)+'">View run</a><button class="btn sm" onclick="openDialog(\'approve\',\''+h(a.id)+'\')">Review request</button></div></div>';}).join('')+(pending.length>2?'<div class="v2-card"><button class="btn sm" onclick="V2.allApprovals=!V2.allApprovals;render()">'+(V2.allApprovals?'Show fewer':'View all '+pending.length+' requests')+'</button></div>':''):'<div class="v2-card"><p>You’re all caught up.</p></div>')+'</section>';}
function v2CoachingCard(){var r=v2Rows()[0];if(!r)return '';return '<section class="panel v2-highlight"><div class="panel-h"><h2>Coaching opportunities</h2>'+v2Link(v2Base()+'/coaching','View all')+'</div><div class="v2-card">'+v2Person(r)+'<h3>Read once. Reuse the result.</h3><p>Repeated file reads are inflating the context. Coach the agent to reuse the last result before reaching for the same tool.</p><div class="v2-meta"><span>12 repeated reads</span><span>3 linked traces</span></div>'+v2Link(v2Base()+'/coaching','Review traces')+'</div></section>';}
function v2ContextCard(){return '<section class="panel"><div class="panel-h"><h2>Shared context</h2>'+v2Link(v2Base()+'/steering','Open')+'</div><div class="v2-card"><h3>One workspace. A consistent brief.</h3><p>Keep the team’s conventions, skills, and working knowledge available across every harness.</p>'+v2Link(v2Base()+'/steering/preview','Preview agent context')+'</div></section>';}
pFleet=function(){
 var state=v2State('Fleet');if(state)return state;
 var rows=S.state==='empty'?[]:v2Rows(),filtered=v2Filter(rows,V2),page=v2Paginate(filtered,V2.page,V2.size),roll=v2Rollup(rows);V2.page=page.page;
 var active=rows.filter(function(r){return ['live','parked','paused'].includes(r.status);}).length;
 var output=v2Header('Fleet','A clear view of your agents and the work moving forward.','<button class="btn" onclick="regStart()">Register agent</button><button class="btn primary" onclick="v2Steer()">Steer agents</button>');
 output+='<div class="v2-metrics">'+v2Metric('Running now',roll.active,'Across '+new Set(rows.filter(function(r){return r.status==='live';}).map(function(r){return r.op;})).size+' operators')+v2Metric('Recent runs',rows.length,'In this workspace')+v2Metric('Attributed spend',usd(roll.cost.toFixed(2)),roll.unmetered+' runs not metered · estimates')+v2Metric('Token efficiency',roll.efficiency===null?'—':roll.efficiency+'%','Input tokens reused from cache')+'</div>';
 output+='<div class="v2-layout"><section class="panel" aria-label="Active agents and recent runs"><div class="panel-h"><h2>Active agents & recent runs</h2><span class="v2-count">'+filtered.length+'</span></div><div class="v2-toolbar"><input id="v2-search" class="v2-search" aria-label="Search runs" placeholder="Search runs, agents, repositories…" value="'+h(V2.q)+'" oninput="v2Search(this.value)">'+v2Options('op','Operator',rows)+v2Options('harness','Harness',rows)+v2Options('repo','Repo',rows)+'<div class="v2-segments"><button aria-pressed="'+(V2.status==='all')+'" onclick="v2Change(\'status\',\'all\')">All runs</button><button aria-pressed="'+(V2.status==='active')+'" onclick="v2Change(\'status\',\'active\')">Active '+active+'</button></div></div>';
 if(V2.selected.size)output+='<div class="v2-bulk"><strong>'+V2.selected.size+' selected</strong><button class="btn sm" onclick="v2Steer()">Steer selected agents</button><button class="btn sm" onclick="V2.selected.clear();render()">Clear</button></div>';
 output+=page.rows.length?'<div class="v2-table-wrap"><table data-lt="v2" data-cards="v2" class="v2-table"><colgroup><col style="width:32px"><col style="width:46%"><col style="width:27%"><col></colgroup><thead><tr><th class="v2-select"><input type="checkbox" aria-label="Select this page" '+(page.rows.every(function(r){return V2.selected.has(r.id);})?'checked':'')+' onchange="v2SelectPage(this.checked)"></th><th scope="col">Run & changes</th><th scope="col">Harness & operator</th><th scope="col">Usage & started</th></tr></thead><tbody>'+page.rows.map(v2TableRow).join('')+'</tbody></table></div>':'<div class="v2-empty"><h3>'+(rows.length?'No matching runs':'Your fleet starts here')+'</h3><p>'+(rows.length?'Try another operator, harness, or repository.':'Register an agent to see its activity here.')+'</p><button class="btn" onclick="'+(rows.length?"V2.q=V2.operator=V2.harness=V2.repo='';V2.status='all';render()":"regStart()")+'">'+(rows.length?'Clear filters':'Register agent')+'</button></div>';
 output+='<div class="v2-pager"><span aria-live="polite">'+page.start+'–'+page.end+' of '+page.total+'</span><label>Rows<select aria-label="Rows per page" onchange="v2Change(\'size\',Number(this.value))">'+[10,25,50].map(function(n){return '<option '+(n===V2.size?'selected':'')+'>'+n+'</option>';}).join('')+'</select></label><div class="row"><button class="btn sm" aria-label="Previous page" '+(page.page===1?'disabled':'')+' onclick="V2.page--;render()">Previous</button><span>'+page.page+' / '+page.pages+'</span><button class="btn sm" aria-label="Next page" '+(page.page===page.pages?'disabled':'')+' onclick="V2.page++;render()">Next</button></div></div></section><aside class="v2-side">'+(S.state==='empty'?'<section class="panel"><div class="panel-h"><h2>Approvals</h2></div><div class="v2-card"><p>You’re all caught up.</p></div></section>':v2Approvals()+v2CoachingCard())+v2ContextCard()+'</aside></div>';
 return output;
};
function v2Coaching(){
 var state=v2State('Operator coaching');if(state)return state;
 var rows=S.state==='empty'?[]:v2Rows();var leads=rows.slice(0,3);
 return v2Header('Operator coaching','Turn the evidence in your traces into better agent habits.',v2Link(v2Base()+'/steering','Shared context'))+
 '<div class="v2-two">'+(leads.length?leads.map(function(r,i){var titles=['Stop repeated file reads','Give the agent a smaller toolset','Make the finish line explicit'],descriptions=['The same file was read 12 times without a change. Reusing the first result keeps later turns smaller.','Only 4 of 18 available tools were used. A focused toolset leaves more room for the task.','The agent continued for 8 calls after the checks passed. A clear stop condition avoids the extra work.'];return '<section class="panel"><div class="panel-h">'+v2Person(r)+'<span class="v2-count">'+(i+3)+' traces</span></div><div class="v2-card"><span class="v2-quiet">'+h(r.agentName)+'</span><h2>'+titles[i]+'</h2><p style="margin-top:12px">'+descriptions[i]+'</p><div class="v2-harness">'+v2Logo(r.harness)+h(r.harnessLabel)+'</div><div class="row">'+'<a class="btn" onclick="V2.runTab=\'trace\'" href="'+v2RunUrl(r)+'">Inspect trace</a>'+'<button class="btn sm" onclick="S.v2CoachingNote=\''+i+'\';openDialog(\'v2-coach\',\''+r.id+'\')">'+(V2.coached.has(r.id)?'Edit coaching note':'Draft coaching note')+'</button></div></div></section>';}).join(''):'<div class="panel v2-empty"><h2>No coaching opportunities yet</h2><p>Recorded runs will give you evidence to learn from.</p></div>')+'</div>';
}
DLG_EXT['v2-coach']=function(){var notes=['Reuse the latest file contents unless the file has changed. Avoid repeated reads with identical inputs.','Start with the tools needed for this task. Add tools only when a concrete step needs them.','Stop after the requested change is verified. Summarize the result and the checks that ran.'];return {t:'Coaching note',s:'Keep a practical next step alongside the trace.',b:'<div class="field"><label for="v2-coach-note">Guidance</label><textarea id="v2-coach-note" rows="5">'+h(V2.coachingDrafts[S.dlgArg]||notes[Number(S.v2CoachingNote)||0])+'</textarea></div>',f:'<button class="btn" onclick="closeDialog()">Cancel</button><button class="btn primary" onclick="V2.coached.add(S.dlgArg);V2.coachingDrafts[S.dlgArg]=document.getElementById(\'v2-coach-note\').value;closeDialog();toast(\'Coaching note saved\',\'allowed\')">Save note</button>'};};
pSpend=function(){
 if(location.hash.split('/')[3]==='coaching')return v2Coaching();
 var state=v2State('Spend');if(state)return state;
 var rows=S.state==='empty'?[]:v2Rows(),roll=v2Rollup(rows),groups=new Map();
 rows.forEach(function(r){var key=V2.spend==='operator'?r.op:V2.spend==='agent'?r.agent:r.harness;var label=V2.spend==='operator'?r.operator:V2.spend==='agent'?r.agentName:r.harnessLabel;
 if(V2.spend==='tool'){[['Model calls',r.cost===null?null:Math.max(0,r.cost-r.toolCost)],['Read files',r.cost===null?null:r.toolCost*.65],['Run checks',r.cost===null?null:r.toolCost*.35]].forEach(function(pair){var g=groups.get(pair[0])||{label:pair[0],cost:0,runs:[],unmetered:0};if(pair[1]!==null)g.cost+=pair[1];else g.unmetered++;g.runs.push(r);groups.set(pair[0],g);});return;}
 var g=groups.get(key)||{label:label,cost:0,runs:[],unmetered:0};g.runs.push(r);if(r.cost!==null)g.cost+=r.cost;else g.unmetered++;groups.set(key,g);});
 var sorted=Array.from(groups.values()).sort(function(a,b){return b.cost-a.cost;});var max=Math.max(1,...sorted.map(function(g){return g.cost;}));
 return v2Header('Spend','Follow every dollar from the operator to the agent and its calls.',v2Link(v2Base()+'/coaching','Find opportunities'))+
 '<div class="v2-metrics">'+v2Metric('Attributed spend',usd(roll.cost.toFixed(2)),'Client-reported estimates')+v2Metric('Cost per metered run',usd((roll.cost/(rows.length-roll.unmetered||1)).toFixed(2)),'Across '+(rows.length-roll.unmetered)+' metered runs')+v2Metric('Cache reuse',roll.efficiency===null?'—':roll.efficiency+'%','Cached input / total input')+v2Metric('Not metered',roll.unmetered,'Excluded from spend totals')+'</div>'+
 '<div class="v2-tabs">'+['operator','agent','harness','tool'].map(function(k){return '<button class="btn" aria-pressed="'+(V2.spend===k)+'" onclick="V2.spend=\''+k+'\';render()">By '+(k==='tool'?'tool call':k)+'</button>';}).join('')+'</div><section class="panel"><div class="panel-h"><h2>Spend by '+(V2.spend==='tool'?'tool call':V2.spend)+'</h2><span class="v2-count">Recent runs</span></div><div class="v2-table-wrap"><table data-lt="v2" data-cards="v2" class="v2-table v2-spend-table"><thead><tr><th>Attribution</th><th>Runs</th><th>Token efficiency</th><th>Spend</th><th></th></tr></thead><tbody>'+sorted.map(function(g){var m=v2Rollup(g.runs);return '<tr><td>'+(V2.spend==='operator'?v2Person(g.runs[0]):'<strong>'+h(g.label)+'</strong>')+'</td><td>'+g.runs.length+'<div class="v2-quiet">'+g.unmetered+' not metered</div></td><td>'+m.efficiency+'%<div class="v2-quiet">cache reuse</div></td><td>'+usd(g.cost.toFixed(2))+'<div class="v2-bar"><i style="width:'+(g.cost/max*100)+'%"></i></div></td><td><button class="btn sm" onclick="V2.spendGroup=\''+h(g.label)+'\';openDialog(\'v2-spend\')">View calls</button></td></tr>';}).join('')+'</tbody></table></div>'+(rows.length?'':'<div class="v2-empty">No spend recorded yet.</div>')+'</section>';
};
DLG_EXT['v2-spend']=function(){var list=v2Rows().filter(function(r){return [r.operator,r.agentName,r.harnessLabel,'Model calls','Read files','Run checks'].includes(V2.spendGroup);});return {t:V2.spendGroup,s:'Open a run to inspect its calls and cost.',b:'<div class="v2-list">'+list.slice(0,12).map(function(r){return '<div class="v2-context-row"><div><a href="'+v2RunUrl(r)+'" onclick="closeDialog()">'+h(r.title)+'</a><p>'+h(r.operator)+' · '+r.calls+' calls</p></div><strong>'+(r.cost===null?'Not metered':usd((V2.spendGroup==='Model calls'?Math.max(0,r.cost-r.toolCost):V2.spendGroup==='Read files'?r.toolCost*.65:V2.spendGroup==='Run checks'?r.toolCost*.35:r.cost).toFixed(2)))+'</strong></div>';}).join('')+'</div>',f:'<button class="btn" onclick="closeDialog()">Close</button>'};};
pRun=function(routeInfo){
 var r=V2_RUNS.find(function(x){return x.id===routeInfo.id;});if(!r)return v2OriginalRun(routeInfo);
 if(V2.fullTrace===r.id)return '<button class="btn" style="margin-bottom:16px" onclick="V2.fullTrace=null;render()">Back to run overview</button>'+v2OriginalRun(routeInfo);
 var state=v2State(r.title);if(state)return state;
 S.frameRun=r.id;
 var output=v2Header(r.title,r.description,v2Link(v2Base(),'Back to fleet')+'<button class="btn primary" onclick="V2.selected=new Set([\''+r.id+'\']);v2Steer()">Steer agent</button>');
 output+='<div class="v2-metrics">'+v2Metric('Run status',({live:'Running',parked:'Waiting',paused:'Paused',sealed:'Completed',halted:'Stopped',compacted:'Completed'}[r.status]||r.status),r.agentName)+v2Metric('Changes','+'+r.added+' / −'+r.removed,r.files+' files changed')+v2Metric('Run spend',v2Money(r),r.cost===null?'Provider usage unavailable':'Client-reported estimate')+v2Metric('Cache reuse',Math.round(r.cached/r.input*100)+'%',r.cached.toLocaleString()+' cached input tokens')+'</div>';
 output+='<div class="v2-tabs">'+['overview','trace','changes'].map(function(t){return '<button class="btn" aria-pressed="'+(V2.runTab===t)+'" onclick="V2.runTab=\''+t+'\';render()">'+t[0].toUpperCase()+t.slice(1)+'</button>';}).join('')+'</div><div class="v2-detail-grid"><section class="panel"><div class="panel-h"><h2>'+({overview:'What this run is doing',trace:'Trace activity',changes:'Repository changes'}[V2.runTab])+'</h2></div>';
 if(V2.runTab==='overview')output+='<div class="v2-card"><p class="v2-description">'+h(r.description)+'</p><div class="v2-meta"><a href="'+v2Base()+'/repositories">'+h(r.repo)+'</a>'+(r.pr?'<span>Pull request #'+r.pr+'</span>':'<span>No pull request</span>')+'</div><h3>Next step</h3><p>'+(r.status==='sealed'?'Review the completed change and its verification.':'Finish the focused checks and summarize the result for '+h(r.operator.split(' ')[0])+'.')+'</p></div>';
 if(V2.runTab==='trace')output+='<div class="v2-card"><button class="btn" onclick="V2.fullTrace=\''+r.id+'\';render()">Open full trace & replay</button></div><ol class="v2-timeline">'+[['Task received',r.title],['Context loaded','Workspace conventions and relevant files added to the context.'],['Tool call · read files',r.file+' · '+(r.input/1000).toFixed(1)+'k input tokens'],['Change prepared','Updated '+r.files+' files; '+r.added+' lines added and '+r.removed+' removed.'],['Verification',r.status==='sealed'?'Focused checks completed.':'Checking the behavior affected by the change.']].map(function(e,i){return '<li>'+v2Time(new Date(new Date(r.started).getTime()+i*60000).toISOString())+'<div><strong>'+h(e[0])+'</strong><p>'+h(e[1])+'</p></div></li>';}).join('')+'</ol>';
 if(V2.runTab==='changes')output+='<div class="v2-card"><h3>'+h(r.repo)+'</h3><p>'+(r.pr?'Pull request #'+r.pr:'Working changes')+' · '+r.files+' files</p><p class="v2-quiet">'+h(r.description)+'</p></div><div class="v2-diff"><span>'+h(r.file)+(r.files>1?' and '+(r.files-1)+' related files':'')+'</span><span><b class="v2-add">+'+r.added+'</b> <b class="v2-remove">−'+r.removed+'</b></span></div>';
 output+='</section><aside class="v2-side"><section class="panel"><div class="panel-h"><h2>Run details</h2></div><div class="v2-card">'+v2Harness(r)+v2Person(r)+'<h3>Started · UTC</h3>'+v2Time(r.started)+'<h3>Token usage</h3><p>'+r.input.toLocaleString()+' input · '+r.output.toLocaleString()+' output<br>'+r.cached.toLocaleString()+' cached input</p><h3>Calls</h3><p>'+r.calls+' tool calls · '+(r.cost===null?'not metered':usd(r.toolCost.toFixed(2))+' estimated tool cost')+'</p></div></section></aside></div>';
 return output;
};
pSteering=function(){
 var segments=location.hash.split('/');
 if(segments[4])return v2OriginalSteering();
 var state=v2State('Shared context');if(state)return state;
 var records=S.state==='empty'?[]:RECORDS.filter(function(r){return r.status==='published';}).slice(0,8);
 return v2Header('Shared context','Give every agent the knowledge and guidance your team works from.','<button class="btn" onclick="openSteerFleet()">Steer agents</button><button class="btn primary" onclick="wzOpen(\'record\')">Create record</button>')+
 '<div class="v2-tabs">'+[['records','Records'],['skills','Skills'],['memory','Memory'],['preview','Preview context']].map(function(p){return v2Link(v2Base()+'/steering/'+p[0],p[1]);}).join('')+'</div><div class="v2-detail-grid"><section class="panel"><div class="panel-h"><h2>Published context</h2>'+v2Link(v2Base()+'/steering/records','View all')+'</div>'+(records.length?records.map(function(r){return '<div class="v2-context-row"><div><strong>'+h(r.title||r.name||r.label||r.st||r.id)+'</strong><p>'+h(r.kind||'Workspace guidance')+'</p></div>'+v2Link(v2Base()+'/steering/records/'+r.id,'Open')+'</div>';}).join(''):'<div class="v2-empty"><p>No context published yet.</p></div>')+'</section><aside class="v2-side"><section class="panel"><div class="panel-h"><h2>Across your harnesses</h2></div><div class="v2-card"><p>Preview the context each agent will receive before you publish a change.</p>'+Object.keys(V2_HARNESSES).map(function(key){return '<div class="v2-harness">'+v2Logo(key)+h(V2_HARNESSES[key].label)+'</div>';}).join('')+v2Link(v2Base()+'/steering/preview','Preview context')+'</div></section></aside></div>';
};
route=function(){var r=v2OriginalRoute();if(location.hash.split('/')[3]==='coaching')r.page='spend';return r;};
sidebar=function(r){
 var original=v2OriginalSidebar(r),base=v2Base(),isCoaching=location.hash.split('/')[3]==='coaching';
 var sections=[['Workspace',[
  ['fleet','Fleet',base],['scenarios','Operator coaching',base+'/coaching'],['spend','Spend',base+'/spend'],['steering','Shared context',base+'/steering']]],
 ['Manage', [['agents','Agents',base+'/agents'],['tools','Tools',base+'/tools'],['repo','Repositories',base+'/repositories']]],
 ['Organization',[['organization','Organization','#/'+ORG.slug],['billing','Billing','#/'+ORG.slug+'/billing'],['audit','Audit','#/'+ORG.slug+'/audit']]]];
 var nav=sections.map(function(s){return '<div class="navlabel">'+s[0]+'</div>'+s[1].map(function(e){var current=e[1]==='Operator coaching'?isCoaching:e[1]==='Spend'?r.page==='spend'&&!isCoaching:e[0]==='repo'?r.page==='repositories':r.page===e[0];return '<a class="navitem" '+(current?'aria-current="page"':'')+' href="'+h(e[2])+'"><span class="ic">'+icon(e[0])+'</span>'+e[1]+'</a>';}).join('');}).join('');
 return original.replace(/<nav>[\s\S]*?<\/nav>/,'<nav>'+nav+'</nav>').replace(/<span class="mono dim"[^>]*>[^<]* plane<\/span>/,'<span class="v2-quiet">Workspace connected</span>');
};
// Present date and time as two unbreakable units, and keep wire formats out of list views.
// Editors, snippets, dialogs and creation wizards are deliberately excluded.
function v2Polish(){
 var pg=document.getElementById('pg');if(!pg)return;
 var page=route().page;
 var descriptions={agents:'Manage the agents working with your team.',tools:'Connect the tools your agents need.',repositories:'Code, context, and pull requests across your workspace.',steering:'Manage the guidance your agents receive.',organization:'Your team and workspace settings.',billing:'Plans, invoices, and payment details.',audit:'Review activity across your organization.'};
 if(descriptions[page]&&!(page==='steering'&&!location.hash.split('/')[4])){var subtitle=pg.querySelector('.phead .t > p:not(.eyebrow)');if(subtitle)subtitle.textContent=descriptions[page];}
 pg.querySelectorAll('.note,.callout,.dim,.panel-h .b').forEach(function(node){if(!node.closest('pre,code,.wizard,[role=dialog]')&&/\b(mockup|fixtures?|demo only|in this demo|implementation detail|Postgres registry)\b/i.test(node.textContent))node.remove();});
 var walker=document.createTreeWalker(pg,NodeFilter.SHOW_TEXT),nodes=[];
 while(walker.nextNode()){var node=walker.currentNode;if(!node.parentElement.closest('time,pre,code,textarea,script,style,.wizard,[contenteditable]')&&/\b2026-\d{2}-\d{2}(?:[ T]\d{2}:\d{2}(?::\d{2})?Z?)?\b/.test(node.textContent))nodes.push(node);}
 nodes.forEach(function(node){var text=node.textContent,regex=/\b(2026-\d{2}-\d{2})(?:[ T](\d{2}:\d{2})(?::\d{2})?Z?)?\b/g,last=0,m,fragment=document.createDocumentFragment();while((m=regex.exec(text))){fragment.append(text.slice(last,m.index));var span=document.createElement('span');if(m[2])span.innerHTML=v2Time(m[1]+'T'+m[2]+':00Z');else{span.className='v2-time';span.textContent=v2Timestamp(m[1]+'T00:00:00Z').date;span.style.whiteSpace='nowrap';}fragment.append(span);last=regex.lastIndex;}fragment.append(text.slice(last));node.replaceWith(fragment);});
 var clocks=document.createTreeWalker(pg,NodeFilter.SHOW_TEXT),clockNodes=[];
 while(clocks.nextNode()){var cn=clocks.currentNode;if(!cn.parentElement.closest('time,pre,code,textarea,.wizard,[contenteditable]')&&/^\s*\d{2}:\d{2}(?::\d{2})?Z?\s*$/.test(cn.textContent))clockNodes.push(cn);}
 clockNodes.forEach(function(cn){var date=new Date(STORY_NOW).toISOString().slice(0,10),clock=cn.textContent.trim().replace(/Z$/,'');if(clock.length===5)clock+=':00';var span=document.createElement('span');span.innerHTML=v2Time(date+'T'+clock+'Z');cn.replaceWith(span);});
 var crumbsNode=document.querySelector('.crumbs');if(crumbsNode&&(location.hash.split('/')[3]==='coaching'||page==='steering')){var b=crumbsNode.querySelector('b:last-child');if(b)b.textContent=page==='steering'?'Shared context':'Operator coaching';}
 document.title=(location.hash.split('/')[3]==='coaching'?'Operator coaching':page==='fleet'?'Fleet':page==='steering'?'Shared context':page[0].toUpperCase()+page.slice(1))+' · Oxagen';
}
render=function(){v2OriginalRender();v2Polish();};
mobileNav=function(r){
 var base=v2Base(),coaching=location.hash.split('/')[3]==='coaching';
 return '<nav class="mnav" aria-label="Primary">'+[
 ['fleet','Fleet',base,r.page==='fleet'||r.page==='run'],
 ['scenarios','Coaching',base+'/coaching',coaching],
 ['spend','Spend',base+'/spend',r.page==='spend'&&!coaching],
 ['steering','Context',base+'/steering',r.page==='steering'||r.page==='skills']
 ].map(function(e){return '<a class="mn" '+(e[3]?'aria-current="page"':'')+' href="'+h(e[2])+'"><span class="ic">'+icon(e[0])+'</span><span>'+e[1]+'</span></a>';}).join('')+'<button class="mn" onclick="S.side=true;render()"><span class="ic">'+icon('more')+'</span><span>More</span></button></nav>';
};
