// generated by tools/build-stories.mjs from mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";
import spec from "../../pages/run-evidence.md?raw";

export default {
  title: "Oxagen/Runs/Evidence",
  tags: ["autodocs"],
  argTypes,
  args: { shell: "desktop", theme: "system", product: true, hash: "#/a-intel/core-platform/runs/run_01K5RS7M2E8FJ3QW/evidence" },
  parameters: { docs: { description: { component: spec } } },
  render: view,
};

export const Loaded = { name: "Loaded", args: { state: "loaded" } };
export const LoadedMobile = { name: "Loaded · mobile", args: { state: "loaded", shell: "mobile" } };
export const LoadedFuture = { name: "Loaded · future-only fields marked", args: { state: "loaded", future: true } };
