// generated by tools/build-stories.mjs from mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";
import spec from "../../pages/skills-off.md?raw";

export default {
  title: "Mission Control/Workspace/Steering · Skills · off (the default)",
  tags: ["autodocs"],
  argTypes,
  args: { shell: "desktop", theme: "system", product: true, hash: "#/a-intel/finops/steering/skills" },
  parameters: { docs: { description: { component: spec } } },
  render: view,
};

export const Loaded = { name: "Loaded", args: { state: "loaded" } };
export const LoadedMobile = { name: "Loaded · mobile", args: { state: "loaded", shell: "mobile" } };
