// generated by tools/build-stories.mjs from mockups/future_state_mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";

export default {
  title: "Scenarios/W1 Sixty Seconds to Governed",
  argTypes,
  args: { shell: "desktop", theme: "system", product: false, hash: "#/a-intel/core-platform/scenarios/sixty-seconds-to-governed/1" },
  render: view,
};

export const Step1 = { name: "Step 1" };
