// generated by tools/build-stories.mjs from mockups/future_state_mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";

export default {
  title: "Scenarios/W6 It learned, you approved, it changed",
  argTypes,
  args: { shell: "desktop", theme: "system", product: false, hash: "#/a-intel/core-platform/scenarios/learned-approved-changed/1" },
  render: view,
};

export const Step1 = { name: "Step 1" };
