// generated by tools/build-stories.mjs from mockups/catalog.mjs; do not edit

import { view } from "../_view.js";

// Still hand-written, not in the master: W13, the interjection and skills (docs/w13-in-the-loop-scenario.md).
export default { title: "Hand-drawn/W13 In the Loop", render: view };

export const W13 = { name: "In the Loop", args: { file: "./w13-in-the-loop.html", product: false, shell: "desktop", theme: "system", hash: "" } };
