// generated by tools/build-stories.mjs from mockups/catalog.mjs; do not edit

import { view, argTypes } from "./_view.js";
import { HOME } from "../catalog.mjs";

// The product build: every page, dialog and auth screen with the mockup chrome taken off.
export default {
  title: "Oxagen/Product",
  argTypes,
  args: { state: "loaded", theme: "system", product: true, hash: HOME },
  render: view,
};

export const Desktop = { args: { shell: "desktop" } };
export const Mobile = { args: { shell: "mobile" } };
export const WithMockupChrome = { name: "With the mockup chrome", args: { shell: "desktop", product: false } };
