// generated by tools/build-stories.mjs from mockups/future_state_mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";
import spec from "../../pages/reset-password.md?raw";

export default {
  title: "Future state/Auth/Reset password",
  tags: ["autodocs"],
  argTypes,
  args: { shell: "desktop", theme: "system", product: true, hash: "#/welcome/reset" },
  parameters: { docs: { description: { component: spec } } },
  render: view,
};

export const Loaded = { name: "Loaded", args: { state: "loaded" } };
export const Loading = { name: "Loading", args: { state: "loading" } };
export const Error = { name: "Error", args: { state: "error" } };
export const AccessDenied = { name: "Access denied", args: { state: "denied" } };
export const LoadedMobile = { name: "Loaded · mobile", args: { state: "loaded", shell: "mobile" } };
export const LoadingMobile = { name: "Loading · mobile", args: { state: "loading", shell: "mobile" } };
export const ErrorMobile = { name: "Error · mobile", args: { state: "error", shell: "mobile" } };
export const AccessDeniedMobile = { name: "Access denied · mobile", args: { state: "denied", shell: "mobile" } };
