#!/usr/bin/env node
// Writes the Storybook stories from mockups/catalog.mjs: one file per page (a story per state,
// desktop and mobile, the page's spec on its Docs tab), one per scenario, and the product build.
// Storybook indexes named exports statically, so the files are written rather
// than built at run time; this script keeps them equal to the catalog.
//
//   node tools/build-stories.mjs           # write mockups/stories/**
//   node tools/build-stories.mjs --check   # exit 1 if any story file is not what the catalog produces
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync, unlinkSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const check = args.includes("--check");
// --dir mockups/future_state_mockups --title "Future state" writes that version's stories from its own catalog.
const BASE = args.includes("--dir") ? args[args.indexOf("--dir") + 1] : "mockups";
const TITLE = args.includes("--title") ? args[args.indexOf("--title") + 1] : "Oxagen";
const { PAGES, SCENARIOS, STATE_WORD, scenarioHash } = await import(pathToFileURL(path.join(root, BASE, "catalog.mjs")).href);
const DIR = path.join(root, BASE, "stories");
const HEAD = `// generated by tools/build-stories.mjs from ${BASE}/catalog.mjs; do not edit\n`;
const exportName = st => STATE_WORD[st].replace(/ (\w)/g, (_, c) => c.toUpperCase()).replace(/^\w/, c => c.toUpperCase());

const outs = new Map();

for (const p of PAGES) {
  const hasSpec = existsSync(path.join(root, BASE, "pages", p.id + ".md"));
  const lines = [HEAD,
    `import { view, argTypes } from "../_view.js";`,
    hasSpec ? `import spec from "../../pages/${p.id}.md?raw";` : `const spec = "";`,
    ``,
    `export default {`,
    `  title: ${JSON.stringify(`${TITLE}/${p.group}/${p.title}`)},`,
    `  tags: ["autodocs"],`,
    `  argTypes,`,
    `  args: { shell: "desktop", theme: "system", product: true, hash: ${JSON.stringify(p.hash)} },`,
    `  parameters: { docs: { description: { component: spec } } },`,
    `  render: view,`,
    `};`,
    ``];
  const label = st => STATE_WORD[st][0].toUpperCase() + STATE_WORD[st].slice(1);
  for (const st of p.states) lines.push(`export const ${exportName(st)} = { name: ${JSON.stringify(label(st))}, args: { state: ${JSON.stringify(st)} } };`);
  for (const st of p.states) lines.push(`export const ${exportName(st)}Mobile = { name: ${JSON.stringify(label(st) + " · mobile")}, args: { state: ${JSON.stringify(st)}, shell: "mobile" } };`);
  outs.set(`pages/${p.id}.stories.js`, lines.join("\n") + "\n");
}

for (const s of SCENARIOS) {
  outs.set(`scenarios/w${s.n}-${s.id}.stories.js`, [HEAD,
    `import { view, argTypes } from "../_view.js";`,
    ``,
    `export default {`,
    `  title: ${JSON.stringify(`Scenarios/W${s.n} ${s.title}`)},`,
    `  argTypes,`,
    `  args: { shell: "desktop", theme: "system", product: false, hash: ${JSON.stringify(scenarioHash(s))} },`,
    `  render: view,`,
    `};`,
    ``,
    `export const Step1 = { name: "Step 1" };`,
    ``].join("\n"));
}

outs.set("product.stories.js", [HEAD,
  `import { view, argTypes } from "./_view.js";`,
  `import { HOME } from "../catalog.mjs";`,
  ``,
  `// The product build: every page, dialog and auth screen with the mockup chrome taken off.`,
  `export default {`,
  `  title: ${JSON.stringify(`${TITLE}/Product`)},`,
  `  argTypes,`,
  `  args: { state: "loaded", theme: "system", product: true, hash: HOME },`,
  `  render: view,`,
  `};`,
  ``,
  `export const Desktop = { args: { shell: "desktop" } };`,
  `export const Mobile = { args: { shell: "mobile" } };`,
  `export const WithMockupChrome = { name: "With the mockup chrome", args: { shell: "desktop", product: false } };`,
  ``].join("\n"));

// A generated file the catalog no longer produces is stale; it goes.
const stale = [];
for (const sub of ["pages", "scenarios", "."]) {
  const d = path.join(DIR, sub);
  if (!existsSync(d)) continue;
  for (const f of readdirSync(d)) {
    const rel = sub === "." ? f : `${sub}/${f}`;
    if (/\.stories\.js$/.test(f) && !outs.has(rel)) stale.push(rel);
  }
}

let failed = 0;
for (const [file, out] of outs) {
  const dst = path.join(DIR, file);
  if (check) {
    if (!(existsSync(dst) && readFileSync(dst, "utf8") === out)) { console.log(`DIFF ${BASE}/stories/${file}`); failed++; }
  } else {
    mkdirSync(path.dirname(dst), { recursive: true });
    writeFileSync(dst, out);
  }
}
for (const f of stale) {
  if (check) { console.log(`STALE ${BASE}/stories/${f}`); failed++; }
  else { unlinkSync(path.join(DIR, f)); console.log(`removed stale ${BASE}/stories/${f}`); }
}
if (check) {
  if (failed) { console.error(`\n${failed} story file(s) differ from the catalog. Run: node tools/build-stories.mjs`); process.exit(1); }
  console.log(`ok   ${outs.size} story files match the catalog`);
} else {
  console.log(`wrote ${outs.size} story files`);
}
