#!/usr/bin/env node
// W1–W11 and W13 are not separate designs. Each one is mc.html, booted into its guided scenario.
//
//   node tools/build-w.mjs           # regenerate every w*.html from mc.html
//   node tools/build-w.mjs --check   # exit 1 if any w*.html is not exactly what mc.html produces
//
// A W file differs from mc.html in two places only: its <title>, and the hash it opens on
// when the URL carries none. Everything else, including every component, token, dataset and
// dialog, is mc.html byte for byte, so a W file cannot drift from the design it demonstrates.
// To change what a W file shows, change mc.html (the page, or its SCENARIOS entry) and rebuild.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

// file, the SCENARIOS id it opens on, and its title. The scenario's own workspace comes from
// mc.html, so the boot hash is read out of the file rather than repeated here.
export const W = [
  ["w1-sixty-seconds-to-governed.html", "sixty-seconds-to-governed", "Sixty Seconds to Governed"],
  ["w2-stop-it-steer-it.html", "stop-it-steer-it", "Stop It. Steer It."],
  ["w3-money-asked.html", "money-asked", "Money Asked, A Human Answered"],
  ["w4-flight-recorder.html", "flight-recorder", "Oxagen Flight Recorder"],
  ["w5-proven-not-claimed.html", "proven-not-claimed", "Proven, Not Claimed"],
  ["w6-learned-approved-changed.html", "learned-approved-changed", "It learned, you approved, it changed"],
  ["w8-every-dollar-every-operator.html", "every-dollar-every-operator", "Every Dollar, Every Operator"],
  ["w9-toolbelt-governed.html", "toolbelt-governed", "The Toolbelt, Governed"],
  ["w10-cio-console.html", "cio-console", "The CIO's Console"],
  ["w11-assistant-and-account.html", "assistant-and-account", "The Assistant on Every Page, and the Account"],
  ["w13-in-the-loop.html", "in-the-loop", "In the Loop"],
];

// Only build when run directly; tools/check-scenarios.mjs imports W from here.
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) main();

function main() {
  const mc = readFileSync(path.join(root, "mc.html"), "utf8");

  function once(haystack, needle, what) {
    const n = haystack.split(needle).length - 1;
    if (n !== 1) throw new Error(`mc.html: expected exactly one ${what}, found ${n}`);
  }

  const TITLE = "<title>The Ten Pages</title>";
  // The org slug is read from the file: the tenant is renamed by tools/build.py, not here.
  const slugM = mc.match(/var ORG = \{slug:"([a-z0-9-]+)"/);
  if (!slugM) throw new Error("mc.html: no ORG slug");
  const SLUG = slugM[1];
  const BOOT = `if(!location.hash)location.hash=BOOT.hash||"#/${SLUG}/core-platform";`;
  once(mc, TITLE, "title");
  once(mc, BOOT, "boot line");

  // The workspace each scenario lives in, read from SCENARIOS so the two can never disagree.
  function scenarioWs(id) {
    // Either inside the literal (  "id":{ title:"…", ws:"…") or in its slot (SCENARIOS["id"]={title:"…", ws:"…").
    const m = mc.match(new RegExp(`(?:\\n\\s*"${id}":|SCENARIOS\\["${id}"\\]\\s*=\\s*)\\{\\s*title:"[^"]*",\\s*ws:"([a-z0-9-]+)"`));
    if (!m) throw new Error(`mc.html: SCENARIOS has no "${id}" entry (or it does not declare title then ws)`);
    return m[1];
  }

  const esc = s => s.replace(/&/g, "&amp;").replace(/</g, "&lt;");
  // Build every output before writing any, so a missing scenario leaves no half-regenerated set.
  const outs = W.map(([file, id, title]) => {
    const hash = `#/${SLUG}/${scenarioWs(id)}/scenarios/${id}/1`;
    const out = mc
      .replace(TITLE, () => `<title>${esc(title)}</title>`)
      .replace(BOOT, () => `if(!location.hash)location.hash=BOOT.hash||"${hash}"; /* generated by tools/build-w.mjs from mc.html */`);
    return { file, hash, out };
  });
  let failed = 0;
  for (const { file, hash, out } of outs) {
    const dst = path.join(root, file);
    if (check) {
      const same = existsSync(dst) && readFileSync(dst, "utf8") === out;
      console.log(`${same ? "ok  " : "DIFF"} ${file}  ${hash}`);
      if (!same) failed++;
    } else {
      writeFileSync(dst, out);
      console.log(`wrote ${file}  ${hash}`);
    }
  }
  if (failed) {
    console.error(`\n${failed} W file(s) differ from mc.html. Run: node tools/build-w.mjs`);
    process.exit(1);
  }
}
