// generated by tools/build-stories.mjs from mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";

export default {
  title: "Scenarios/W14 Done Means Done",
  argTypes,
  args: { shell: "desktop", theme: "system", product: false, hash: "#/a-intel/core-platform/scenarios/done-means-done/1" },
  render: view,
};

export const Step1 = { name: "Step 1" };
