// generated by tools/build-stories.mjs from mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";

export default {
  title: "Scenarios/W3 Money Asked, A Human Answered",
  argTypes,
  args: { shell: "desktop", theme: "system", product: false, hash: "#/a-intel/finops/scenarios/money-asked/1" },
  render: view,
};

export const Step1 = { name: "Step 1" };
