// generated by tools/build-stories.mjs from mockups/catalog.mjs; do not edit

import { view, argTypes } from "../_view.js";

export default {
  title: "Scenarios/W4 Oxagen Flight Recorder",
  argTypes,
  args: { shell: "desktop", theme: "system", product: false, hash: "#/a-intel/core-platform/scenarios/flight-recorder/1" },
  render: view,
};

export const Step1 = { name: "Step 1" };
